[package]
edition = "2018"
name = "blue"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1.0"
prost = "0.8.0"
serde_json = "1"
structopt = "0.3"

[build-dependencies]
prost-build = {version = "0.8.0"}
